language: groovy
branches:
  only:
    - master
    - developer
    - migrate-grails3

before_script:
 - chmod +x gradlew
 - chmod +x travis-build.sh

script: ./travis-build.sh

notifications:
  email:
    - marianoekfuri@gmail.com
    - mmicciullo@gmail.com

